import {initLanguage,translate} from './i18n.js';
import {projectDescriptions} from './project-descriptions.js';
import {projectIndex,openProject,projectGeometry} from './projects.js';
import {DesignFiles,encodeDesign,decodeDesign,readShelf,saveToShelf,safeFilename} from './designs.js';
import {catalog,byId,example,validate,footprint,issues,scad,doublePassExample} from './model.js';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const designFiles=new DesignFiles();let folderEntries=[];
const KEY='c4po-optical-bench-v1';let state=example(),selected=null,mode='2d',linkStart=null,connecting=false,drag=null,history=[],future=[],view=null,renderer=null,worker=null,timer=null,renderTimeout=null,renderCache=new Map(),currentSTL=null,currentKey=null,toastTimer;
try{const saved=localStorage.getItem(KEY);if(saved)state=validate(JSON.parse(saved));}catch(e){setTimeout(()=>toast('Could not restore the saved layout. Loaded the example.'),100);}
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6000);}
function checkpoint(){history.push(JSON.stringify(state));if(history.length>60)history.shift();future=[];}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));$('save-status').textContent='Saved on this device';}catch{$('save-status').textContent='Use Save layout to keep your work';}}
function commit(){persist();currentSTL=null;currentKey=null;render();schedule();}
function edit(fn){const before=structuredClone(state);try{fn();validate(state);history.push(JSON.stringify(before));future=[];commit();}catch(e){state=before;render();toast(e.message);}}
function active(){return state.components.find(c=>c.id===selected);}
function normalize(a){return ((a+180)%360+360)%360-180;}
function symbol(d){if(d.kind==='aom')return '<rect x="-10" y="-15" width="20" height="30" rx="2" fill="#e4b169" stroke="#996c28"/><path d="M-14 0H14" stroke="#c35e47" stroke-width="1"/><text x="0" y="-5" font-size="5" text-anchor="middle" fill="#654817">AOM</text>';if(d.kind==='pbs')return '<rect x="-7" y="-7" width="14" height="14" fill="#a9cbd8" stroke="#377c98"/><path d="M-7 -7L7 7" stroke="#377c98"/>';if(d.kind==='waveplate')return '<ellipse rx="4" ry="11" fill="#dac9ea" stroke="#8966a0"/><path d="M0 -8V8" stroke="#8966a0"/>';if(d.kind==='fiber')return '<rect x="-9" y="-10" width="10" height="20" fill="#607f91"/><path d="M1 0H13" stroke="#dc8469" stroke-width="2"/>';if(d.kind==='detector')return '<rect x="-9" y="-11" width="18" height="22" fill="#668797"/><circle r="4" fill="#183443"/>';if(d.kind==='isolator')return '<rect x="-14" y="-8" width="28" height="16" rx="5" fill="#88aeb2"/><path d="M-7 0H7L3 -3M7 0L3 3" stroke="#305c64" fill="none"/>';if(d.kind==='mirror')return '<path d="M-3 -11 L-3 11" stroke="#78c9cc" stroke-width="4"/><path d="M-6 -10 L-6 10" stroke="#2d5869" stroke-width="2"/>';if(d.kind==='lens')return '<ellipse cx="0" cy="0" rx="3" ry="11" fill="#85cbd58a" stroke="#2d91a5" stroke-width="1.2"/>';return '<path d="M0 -12 V-4 M0 4 V12" stroke="#547585" stroke-width="5"/><circle r="2" fill="#fff" stroke="#547585"/>';}
function cardIcon(d){return `<svg viewBox="-22 -22 44 44" aria-hidden="true"><rect x="-16" y="-17" width="27" height="34" rx="4" fill="#e9eef2" stroke="#9cafbb"/><g transform="translate(7 0)">${symbol(d)}</g></svg>`;}
function renderCatalog(){const query=$('catalog-search').value.toLowerCase(),category=$('catalog-category').value,filtered=catalog.filter(d=>!d.hiddenFromLibrary&&(!category||d.category===category)&&`${d.name} ${translate(d.name)} ${d.part} ${d.category} ${translate(d.category)}`.toLowerCase().includes(query));$('catalog').innerHTML=[...new Set(filtered.map(d=>d.category))].map(group=>`<div class="catalog-group">${esc(group)}</div>`+filtered.filter(d=>d.category===group).map(d=>`<button class="component-card" draggable="true" data-type="${d.id}" aria-label="Add ${esc(d.name)}">${cardIcon(d)}<span><b>${esc(d.name)}</b><small>${esc(d.part)}</small></span><span class="plus">+</span></button>`).join('')).join('')||'<p class="muted">No matching components.</p>';}
$('catalog-category').innerHTML+=[...new Set(catalog.filter(c=>!c.hiddenFromLibrary).map(c=>c.category))].map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('catalog-search').oninput=renderCatalog;$('catalog-category').onchange=renderCatalog;renderCatalog();
$('catalog').addEventListener('dragstart',e=>{const b=e.target.closest('[data-type]');if(b){e.dataTransfer.setData('application/c4po-component',b.dataset.type);e.dataTransfer.effectAllowed='copy';}});
$('catalog').addEventListener('click',e=>{const b=e.target.closest('[data-type]');if(b)add(b.dataset.type,state.plate.width/2,state.plate.height/2);});
function add(type,x,y){if(!byId[type])return;edit(()=>{const id=crypto.randomUUID();state.components.push({id,type,label:byId[type].name,x:snap(x,state.plate.width),y:snap(y,state.plate.height),angle:0});selected=id;});}
function snap(n,max){const s=state.plate.snap;return Math.max(0,Math.min(max,Math.round((s?Math.round(n/s)*s:n)*1000)/1000));}
function coordinates(e){const point=new DOMPoint(e.clientX,e.clientY).matrixTransform($('layout').getScreenCTM().inverse());return {x:point.x,y:state.plate.height-point.y};}
$('drawing').addEventListener('dragover',e=>{if(mode==='2d'){e.preventDefault();e.dataTransfer.dropEffect='copy';}});
$('drawing').addEventListener('drop',e=>{e.preventDefault();if(mode!=='2d')return;const p=coordinates(e);add(e.dataTransfer.getData('application/c4po-component'),p.x,p.y);});
function fit(){const p=state.plate;view={x:-22,y:-28,w:p.width+44,h:p.height+56};if(mode==='3d')renderer?.fit();draw();}
function draw(){const p=state.plate;if(!view)view={x:-22,y:-28,w:p.width+44,h:p.height+56};const svg=$('layout');svg.setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`);
 let s=`<defs><pattern id="grid-dots" width="${p.grid}" height="${p.grid}" patternUnits="userSpaceOnUse"><circle cx="0" cy="0" r="0.48" fill="#becbd2"/></pattern><marker id="arrow" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L6 3L0 6" fill="none" stroke="#df775e" stroke-width="1"/></marker></defs><rect x="0" y="0" width="${p.width}" height="${p.height}" fill="#fff" stroke="#b7c6ce" stroke-width=".7" rx="1.2"/><rect x="0" y="0" width="${p.width}" height="${p.height}" fill="url(#grid-dots)"/>`;
 if(p.cornerHoles)for(const x of[12.7,p.width-12.7])for(const y of[12.7,p.height-12.7])s+=`<circle cx="${x}" cy="${y}" r="3.302" fill="#edf2f5" stroke="#a6b9c3" stroke-width=".5"/>`;
 for(let x=0;x<=p.width;x+=p.grid*2)s+=`<text x="${x}" y="${p.height+9}" font-size="3.4" fill="#8b9ca8" text-anchor="middle">${Math.round(x*10)/10}</text>`;
 for(let y=0;y<=p.height;y+=p.grid*2)s+=`<text x="-6" y="${p.height-y+1}" font-size="3.4" fill="#8b9ca8" text-anchor="end">${Math.round(y*10)/10}</text>`;
 if(state.view.showBeams)state.connections.forEach(([a,b],i)=>{const ca=state.components.find(c=>c.id===a),cb=state.components.find(c=>c.id===b);if(ca&&cb)s+=`<g class="beam" data-beam="${i}"><title>Double-click to remove beam guide</title><line x1="${ca.x}" y1="${p.height-ca.y}" x2="${cb.x}" y2="${p.height-cb.y}" stroke="transparent" stroke-width="6"/><line x1="${ca.x}" y1="${p.height-ca.y}" x2="${cb.x}" y2="${p.height-cb.y}" stroke="#df775e" stroke-width=".8" marker-end="url(#arrow)"/></g>`;});
 for(const c of state.components){const d=byId[c.type],sel=c.id===selected,outline=footprint(c).map(([x,y])=>`${x},${p.height-y}`).join(' ');s+=`<g class="mount" data-id="${esc(c.id)}" tabindex="0" role="button" aria-label="${esc(c.label)}, X ${c.x}, Y ${c.y}"><title>${esc(c.label)} · ${d.part}</title><polygon class="envelope" points="${outline}" fill="${sel?'#d8edebbb':'#e4ebefaa'}" stroke="${sel?'#087c80':'#91a7b5'}" stroke-width="${sel?'.9':'.45'}" stroke-dasharray="${sel?'0':'1.5 1'}"/><g transform="translate(${c.x} ${p.height-c.y}) rotate(${-c.angle})">${symbol(d)}<path d="M-2 0H2M0 -2V2" stroke="#123b4b" stroke-width=".45"/></g><text x="${c.x}" y="${p.height-c.y+24}" font-size="4" fill="${sel?'#087c80':'#506b7e'}" text-anchor="middle">${esc(c.label)}</text>${linkStart===c.id?`<circle cx="${c.x}" cy="${p.height-c.y}" r="5" fill="none" stroke="#df775e" stroke-width="1"/>`:''}</g>`;}
 svg.innerHTML=s;
}
function render(){draw();const p=state.plate,c=active();$('project-name').value=state.name;$('plate-label').textContent=`${p.width} × ${p.height} mm plate`;$('source-project').hidden=!state.project; if(state.project){$('source-project-name').textContent=state.project.source;$('source-project-notes').textContent=state.project.notes.join(' ');}
 $('component-count').textContent=`${state.components.length} mounts · ${state.connections.length} beam guides`;
 $('assembly').checked=state.view.showMounts;$('show-beams').checked=state.view.showBeams;
 $('selection').hidden=!c;$('selection-empty').hidden=!!c;
 if(c){$('part-name').textContent=byId[c.type].name;$('part-number').textContent=byId[c.type].part;$('part-note').textContent=byId[c.type].sourceAsset?'Imported native component. Rotation is an adjustment to its source orientation. Duplicate to reuse this variant. The plate includes native mounting holes and recesses.':byId[c.type].note||'';for(const k of['label','x','y','angle'])$(k).value=c[k];$('x').max=p.width;$('y').max=p.height;}
 for(const k of['width','height','thickness','beamHeight','grid','snap'])$(k).value=p[k];$('cornerHoles').checked=p.cornerHoles;
 const warnings=issues(state);$('check-summary').textContent=warnings.length?`${warnings.length} item${warnings.length===1?'':'s'} to review`:'No envelope or recess-depth flags';$('issues').innerHTML=warnings.map(x=>`<li>${esc(x)}</li>`).join('');$('undo').disabled=!history.length;$('redo').disabled=!future.length;
}
function select(id){selected=id;if(connecting){if(!linkStart){linkStart=id;toast('Select another mount to connect its optical center.');}else if(linkStart!==id){const start=linkStart;edit(()=>{if(!state.connections.some(e=>e.includes(start)&&e.includes(id)))state.connections.push([start,id]);});linkStart=id;}}render();}
$('layout').addEventListener('pointerdown',e=>{if(e.button!==0&&e.button!==1)return;const node=e.target.closest('[data-id]');if(node&&e.button===0){select(node.dataset.id);if(connecting)return;const p=coordinates(e),c=active();drag={id:c.id,dx:p.x-c.x,dy:p.y-c.y,before:JSON.stringify(state),moved:false};}else if(!e.target.closest('[data-beam]')){selected=null;render();drag={pan:true,x:e.clientX,y:e.clientY,view:{...view}};}$('layout').setPointerCapture(e.pointerId);});
$('layout').addEventListener('pointermove',e=>{if(!drag)return;if(drag.pan){const rect=$('layout').getBoundingClientRect(),scale=Math.min(rect.width/view.w,rect.height/view.h);view.x=drag.view.x-(e.clientX-drag.x)/scale;view.y=drag.view.y-(e.clientY-drag.y)/scale;draw();return;}const p=coordinates(e),c=state.components.find(c=>c.id===drag.id);c.x=snap(p.x-drag.dx,state.plate.width);c.y=snap(p.y-drag.dy,state.plate.height);drag.moved=true;render();});
function endDrag(){if(drag?.moved){history.push(drag.before);future=[];commit();}drag=null;}
$('layout').addEventListener('pointerup',endDrag);$('layout').addEventListener('pointercancel',endDrag);
$('layout').addEventListener('keydown',e=>{const node=e.target.closest('[data-id]');if(node&&['Enter',' '].includes(e.key)){e.preventDefault();select(node.dataset.id);}});
$('layout').addEventListener('dblclick',e=>{const b=e.target.closest('[data-beam]');if(b)edit(()=>state.connections.splice(Number(b.dataset.beam),1));});
$('layout').addEventListener('wheel',e=>{e.preventDefault();const point=new DOMPoint(e.clientX,e.clientY).matrixTransform($('layout').getScreenCTM().inverse()),factor=e.deltaY>0?1.12:1/1.12,newW=view.w*factor;if(newW<30||newW>3000)return;view={x:point.x+(view.x-point.x)*factor,y:point.y+(view.y-point.y)*factor,w:newW,h:view.h*factor};draw();},{passive:false});
function bindField(id,read,write){const commitField=()=>{const value=$(id).type==='number'?Number($(id).value):$(id).value;if(String(read())!==String(value))edit(()=>write(value));};$(id).addEventListener('change',commitField);$(id).addEventListener('blur',commitField);$(id).addEventListener('keydown',e=>{if(e.key==='Enter'){$(id).blur();}});}
for(const k of['label','x','y','angle'])bindField(k,()=>active()?.[k],v=>{if(active())active()[k]=v;});
for(const k of['width','height','thickness','beamHeight','grid','snap'])bindField(k,()=>state.plate[k],v=>{state.plate[k]=Number(v);if(k==='width'||k==='height')view=null;});
$('cornerHoles').onchange=()=>edit(()=>state.plate.cornerHoles=$('cornerHoles').checked);bindField('project-name',()=>state.name,v=>state.name=v||'Untitled layout');
function remove(){if(!selected)return;edit(()=>{state.components=state.components.filter(c=>c.id!==selected);state.connections=state.connections.filter(e=>!e.includes(selected));selected=null;linkStart=null;});}
$('delete').onclick=remove;$('duplicate').onclick=()=>{const c=active();if(c)edit(()=>{const copy={...c,id:crypto.randomUUID(),label:(c.label+' copy').slice(0,60),x:Math.min(c.x+20,state.plate.width),y:Math.min(c.y+20,state.plate.height)};state.components.push(copy);selected=copy.id;});};
function undo(redo=false){const from=redo?future:history,to=redo?history:future;if(!from.length)return;to.push(JSON.stringify(state));state=JSON.parse(from.pop());selected=null;linkStart=null;view=null;commit();}
$('undo').onclick=()=>undo();$('redo').onclick=()=>undo(true);
document.addEventListener('keydown',e=>{if($('design-dialog').open||$('project-dialog').open||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey);}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove();}else if(e.key.toLowerCase()==='r'&&active())edit(()=>active().angle=normalize(active().angle+(e.shiftKey?-15:15)));else if(e.key==='Escape'){connecting=false;linkStart=null;$('connect').classList.remove('active');$('connect').setAttribute('aria-pressed','false');render();}else if(active()&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();edit(()=>{const c=active(),step=state.plate.snap||1;c.x=snap(c.x+({ArrowLeft:-step,ArrowRight:step}[e.key]||0),state.plate.width);c.y=snap(c.y+({ArrowDown:-step,ArrowUp:step}[e.key]||0),state.plate.height);});}});
$('connect').onclick=()=>{connecting=!connecting;linkStart=null;$('connect').classList.toggle('active',connecting);$('connect').setAttribute('aria-pressed',String(connecting));if(connecting)toast('Select two mounts to draw a beam guide. Escape exits.');draw();};$('fit').onclick=fit;
$('clear-beams').onclick=()=>edit(()=>{state.connections=[];linkStart=null;});$('new').onclick=()=>edit(()=>{designFiles.file=null;state=example();state.name='Untitled layout';state.components=[];state.connections=[];selected=null;linkStart=null;view=null;});
function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.style.display='none';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
const filename=()=>state.name.replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,80)||'optical-layout';
function loadDesign(incoming){checkpoint();state=validate(incoming);selected=null;linkStart=null;view=null;commit();fit();}
async function refreshDesigns(){
 $('current-design-name').textContent=`Current design: ${state.name}`;$('update-file').hidden=!designFiles.file;
 $('save-as').hidden=!designFiles.canSaveAs;$('choose-folder').hidden=!designFiles.canChooseFolder;
 $('folder-help').textContent=designFiles.canChooseFolder?'Choose a folder once to save and reopen JSON designs here. Access is limited to the folder you choose.':'This browser does not offer direct folder access. Use Download JSON copy, then Open design to restore it; Chrome and Edge also support choosing a folder.';
 let shelf=[];try{shelf=readShelf();}catch(e){toast(e.message);}
 $('saved-designs').innerHTML=shelf.map((entry,i)=>`<div class="design-row"><span><b>${esc(entry.name)}</b><small>${esc(new Date(entry.savedAt).toLocaleString())}</small></span><button data-saved="${i}">Open</button></div>`).join('');
 $('saved-designs').querySelectorAll('[data-saved]').forEach(b=>b.onclick=()=>{try{const incoming=validate(shelf[Number(b.dataset.saved)].layout);designFiles.file=null;loadDesign(incoming);$('design-dialog').close();toast('Saved design restored.');}catch(e){toast(e.message);}});
 try{folderEntries=await designFiles.entries();$('folder-name').textContent=designFiles.directory?`Folder: ${designFiles.directory.name}`:'Local designs folder';$('save-folder').hidden=!designFiles.directory;$('folder-designs').innerHTML=folderEntries.map((entry,i)=>`<div class="design-row"><b>${esc(entry.name)}</b><button data-file="${i}">Open</button></div>`).join('');$('folder-designs').querySelectorAll('[data-file]').forEach(b=>b.onclick=async()=>{try{loadDesign(await designFiles.open(folderEntries[Number(b.dataset.file)].handle));$('design-dialog').close();toast('File restored. Use Update opened file to save changes.');}catch(e){toast(e.message);}});}catch(e){toast('Could not read the folder: '+e.message);}
}
function openDesigns(){refreshDesigns();$('design-dialog').showModal();}
$('save').onclick=openDesigns;$('designs').onclick=openDesigns;$('close-designs').onclick=()=>$('design-dialog').close();
$('save-browser').onclick=()=>{try{saveToShelf(state);refreshDesigns();toast(`Saved “${state.name}” in this browser.`);}catch(e){toast('Could not save this design: '+e.message);}};
$('download-design').onclick=()=>download(encodeDesign(state),safeFilename(state.name),'application/json');
$('save-as').onclick=async()=>{try{if(await designFiles.saveAs(state)){refreshDesigns();toast('Design saved to your chosen file.');}}catch(e){if(e.name!=='AbortError')toast('Could not save: '+e.message);}};
$('update-file').onclick=async()=>{try{if(await designFiles.save(state))toast('Design file updated.');}catch(e){toast('Could not update the file: '+e.message);}};
$('choose-folder').onclick=async()=>{try{await designFiles.chooseFolder();refreshDesigns();}catch(e){if(e.name!=='AbortError')toast('Could not open folder: '+e.message);}};
$('save-folder').onclick=async()=>{try{const name=await designFiles.saveInFolder(state);refreshDesigns();toast(`Saved ${name}.`);}catch(e){toast('Could not save to folder: '+e.message);}};
$('open').onclick=async()=>{if(typeof window.showOpenFilePicker!=='function'){$('file').click();return;}try{const [handle]=await window.showOpenFilePicker({id:'c4po-designs',multiple:false,types:[{description:'C4PO design',accept:{'application/json':['.json']}}]});loadDesign(await designFiles.open(handle));toast('Design restored.');}catch(e){if(e.name!=='AbortError')toast('Could not open design: '+e.message);}};
$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;try{if(f.size>1000000)throw Error('Design files must be smaller than 1 MB.');const incoming=decodeDesign(await f.text());designFiles.file=null;loadDesign(incoming);toast('Design restored.');}catch(e){toast(e.message);}finally{$('file').value='';}};
$('double-pass').onclick=()=>{designFiles.file=null;loadDesign(doublePassExample());toast('Loaded the editable double-pass starter. Undo returns to your previous layout.');};
let exampleIndex=null;
async function showProjects(){try{exampleIndex=await projectIndex();$('project-category').innerHTML='<option value="">All projects</option>'+[...new Set(exampleIndex.projects.map(p=>p.category))].map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');renderProjects();$('project-inventory').innerHTML=exampleIndex.inventory.filter(e=>!['editable','partial'].includes(e.status)).map(e=>`<li><b>${esc(e.file)}</b><span>${esc(e.reason)}</span></li>`).join('');$('project-dialog').showModal();}catch(e){toast(e.message);}}
function renderProjects(){if(!exampleIndex)return;const query=$('project-search').value.toLowerCase(),category=$('project-category').value;const entries=[{id:'guided-double-pass',name:'Double-pass AOM · beam guide example',source:'Curated from doublepass_aom.scad',category:'AOM layouts',components:18,width:278.4,height:127,notes:['A compact starter with editable beam connections already drawn.'],partial:false},...exampleIndex.projects];const filtered=entries.filter(p=>(!category||p.category===category)&&`${p.name} ${p.source} ${p.category} ${projectDescriptions[p.id]?.join(" ")||""}`.toLowerCase().includes(query));$('project-total').textContent=`${filtered.length} starting layouts`; $('project-cards').innerHTML=filtered.map(p=>`<article class="project-card"><div class="tiny-tag">${esc(p.category)}</div><h3>${esc(p.name)}</h3><code>${esc(p.source)}</code><p class="project-description">${esc(projectDescriptions[p.id]?.[0]||'')}</p><p>${p.components} components · ${p.width} × ${p.height} mm</p>${p.partial?'<span class="project-warning">Source needs review</span>':''}<details><summary>Import notes</summary>${p.notes.map(n=>`<p>${esc(n)}</p>`).join('')}</details><button class="primary" data-project="${esc(p.id)}">Start from this project</button></article>`).join('')||'<p>No matching projects.</p>'; $('project-cards').querySelectorAll('[data-project]').forEach(button=>button.onclick=async()=>{try{button.disabled=true;const incoming=await openProject(button.dataset.project);designFiles.file=null;loadDesign(incoming);$('project-dialog').close();toast('Example loaded. Undo returns to your previous design.');}catch(e){toast(e.message);}finally{button.disabled=false;}});}
$('examples').onclick=showProjects;$('browse-projects').onclick=showProjects;$('close-projects').onclick=()=>$('project-dialog').close();$('project-search').oninput=renderProjects;$('project-category').onchange=renderProjects;
designFiles.restoreFolder();
$('export-scad').onclick=async()=>{try{const snapshot=structuredClone(state);let source=scad(snapshot,true);const files=[...new Set(snapshot.components.flatMap(c=>{const p=byId[c.type];return p.sourceAsset?[p.sourceAsset,p.sourcePreview]:[];}))];const bundle=files.length?await projectGeometry():{};for(const file of files){if(typeof bundle[file]!=='string')throw Error('Missing project geometry: '+file);source=source.replaceAll(`include <${file}>;`,bundle[file]);}for(const c of snapshot.components)for(const [asset,original] of Object.entries(byId[c.type].cutOriginalPaths||{}))source=source.replaceAll(JSON.stringify(asset),JSON.stringify(original));download(source,safeFilename(snapshot.name).replace(/\.json$/,'.scad'),'text/plain');toast('Source saved. Use the original CAD folder for hardware mesh dependencies.');}catch(e){toast('Could not export source: '+e.message);}};
$('export-svg').onclick=()=>{const svg=$('layout').cloneNode(true);svg.removeAttribute('style');svg.setAttribute('xmlns','http://www.w3.org/2000/svg');svg.setAttribute('viewBox',`-22 -28 ${state.plate.width+44} ${state.plate.height+56}`);svg.setAttribute('width',`${state.plate.width+44}mm`);svg.setAttribute('height',`${state.plate.height+56}mm`);download(new XMLSerializer().serializeToString(svg),filename()+'.svg','image/svg+xml');};
function cancel(){worker?.terminate();worker=null;clearTimeout(timer);clearTimeout(renderTimeout);$('cancel-render').hidden=true;$('export-stl').disabled=false;}
function geometryKey(){return JSON.stringify({plate:state.plate,components:state.components});}
function schedule(){cancel();if(mode==='3d'){currentSTL=null;renderer?.clear();updateMounts();$('render-status').textContent='Preparing plate with mounting holes…';timer=setTimeout(()=>generate(false),350);}else $('render-status').textContent='2D layout · dimensions in millimeters';}
async function setMode(next){mode=next;for(const n of['2d','3d']){$('view-'+n).classList.toggle('active',next===n);$('view-'+n).setAttribute('aria-pressed',String(next===n));}$('layout').style.display=next==='3d'?'none':'block';$('three-view').hidden=next!=='3d';$('view3d-controls').hidden=next!=='3d';$('connect').disabled=next==='3d';$('canvas-hint').textContent=next==='3d'?'Drag to orbit · Scroll to zoom · Right-drag to pan':'Drag to position · R to rotate 15° · Delete to remove';if(next==='3d'){try{if(!renderer){const {Viewer}=await import('./viewer.js');renderer=new Viewer($('three-view'));}schedule();}catch(e){toast('3D view unavailable: '+e.message);$('render-status').textContent='3D view unavailable. OpenSCAD export is still available.';}}else{cancel();$('render-status').textContent='2D layout · dimensions in millimeters';}}
$('view-2d').onclick=()=>setMode('2d');$('view-3d').onclick=()=>setMode('3d');$('assembly').onchange=()=>{state.view.showMounts=$('assembly').checked;persist();updateMounts();};$('show-beams').onchange=()=>{state.view.showBeams=$('show-beams').checked;persist();draw();updateBeams();};$('cancel-render').onclick=()=>{cancel();$('render-status').textContent='Generation cancelled. Edit the layout or reopen 3D to retry.';};
function updateBeams(){renderer?.setBeams(state,state.view.showBeams);}
async function updateMounts(){updateBeams();if(renderer)try{await renderer.setMounts(structuredClone(state),$('assembly').checked);}catch(e){toast('Mount preview failed: '+e.message);}}
async function generate(exportFile){
 cancel();const assembly=false,key=geometryKey();
 if(renderCache.has(key)){complete(renderCache.get(key),key,assembly,exportFile);return;}
 $('export-stl').disabled=true;$('cancel-render').hidden=false;$('render-status').textContent='Starting OpenSCAD in your browser…';
 const job=new Worker('./render-worker.js',{type:'module'});worker=job;const timeout=renderTimeout=setTimeout(()=>{if(worker===job){cancel();toast('This render exceeded 10 minutes. Try a smaller layout or desktop OpenSCAD.');$('render-status').textContent='Render timed out';}},600000);
 job.onmessage=({data})=>{if(worker!==job)return;if(data.status){$('render-status').textContent=data.status;return;}clearTimeout(timeout);cancel();if(data.error){$('render-status').textContent='Render failed';toast(data.error);console.error(data.error,data.logs);return;}renderCache.set(key,data.bytes);if(renderCache.size>4)renderCache.delete(renderCache.keys().next().value);complete(data.bytes,key,assembly,exportFile);};
 job.onerror=e=>{clearTimeout(timeout);cancel();$('render-status').textContent='Render failed';toast(e.message||'Could not start the CAD engine.');};job.postMessage({layout:structuredClone(state),assembly});
}
function complete(bytes,key,assembly,exportFile){currentSTL=bytes;currentKey=key;$('render-status').textContent=`${assembly?'Assembly':'Base plate'} rendered · ${(bytes.length/1024).toFixed(0)} KB`;if(mode==='3d'&&renderer){renderer.show(bytes);renderer.resize();updateMounts();}if(exportFile){download(bytes,filename()+'-plate.stl','model/stl');toast('Base plate STL exported in millimeters.');}}

$('export-stl').onclick=()=>generate(true);render();fit();

initLanguage(()=>{renderCatalog();renderProjects();});
