import {beamSegments} from './model.js';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {STLLoader} from 'three/addons/loaders/STLLoader.js';
export class Viewer{
 constructor(host){this.host=host;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#edf2f5');this.camera=new THREE.PerspectiveCamera(38,1,.1,10000);this.camera.up.set(0,0,1);this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.append(this.renderer.domElement);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.scene.add(new THREE.HemisphereLight(0xffffff,0x657587,3));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(-200,-300,500);this.scene.add(light);this.material=new THREE.MeshStandardMaterial({color:0x88a9b4,metalness:.25,roughness:.65,side:THREE.DoubleSide});this.hardwareMaterial=new THREE.MeshStandardMaterial({color:0x2a3d49,metalness:.35,roughness:.5,side:THREE.DoubleSide});this.opticMaterial=new THREE.MeshStandardMaterial({color:0x69c4cc,metalness:.5,roughness:.2});this.mounts=new THREE.Group();this.scene.add(this.mounts);this.beams=new THREE.Group();this.scene.add(this.beams);this.beamMaterial=new THREE.MeshBasicMaterial({color:0xef795c,transparent:true,opacity:.85});this.geometryCache=new Map();this.mountVersion=0;new ResizeObserver(()=>this.resize()).observe(host);this.renderer.setAnimationLoop(()=>{if(host.hidden)return;this.controls.update();this.renderer.render(this.scene,this.camera);});}
 setBeams(layout,visible){for(const child of this.beams.children)child.geometry.dispose();this.beams.clear();if(!visible)return;for(const {start,end} of beamSegments(layout)){const a=new THREE.Vector3(...start),b=new THREE.Vector3(...end),delta=b.clone().sub(a),length=delta.length();if(length<1e-6)continue;const mesh=new THREE.Mesh(new THREE.CylinderGeometry(.4,.4,length,8),this.beamMaterial);mesh.position.copy(a).add(b).multiplyScalar(.5);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());this.beams.add(mesh);}}
 clear(){if(this.mesh){this.scene.remove(this.mesh);this.mesh.geometry.dispose();this.mesh=null;}}
 preview(layout){this.clear();const p=layout.plate,geometry=new THREE.BoxGeometry(p.width,p.height,p.thickness);geometry.translate(p.width/2,p.height/2,-p.beamHeight-p.thickness/2);this.mesh=new THREE.Mesh(geometry,this.material);this.scene.add(this.mesh);this.resize();if(!this.previewInitialized){this.fit();this.previewInitialized=true;}}
 show(bytes){this.clear();const buffer=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),geometry=new STLLoader().parse(buffer);geometry.computeBoundingBox();geometry.computeVertexNormals();this.mesh=new THREE.Mesh(geometry,this.material);this.scene.add(this.mesh);this.resize();this.fit();}
 async setMounts(layout,visible){const version=++this.mountVersion;this.mounts.clear();if(!visible)return;
  this.manifest??=Promise.all(['./cad/mount-scenes.json','./cad/project-scenes.json'].map(url=>fetch(url).then(r=>{if(!r.ok)throw Error('Mount preview library is unavailable.');return r.json();}))).then(([a,b])=>({...a,...b}));const scenes=await this.manifest;
  const groups=await Promise.all(layout.components.map(async c=>{const group=new THREE.Group();group.position.set(c.x,c.y,c.z||0);group.rotation.z=c.angle*Math.PI/180;
   for(const item of scenes[c.type]){let geometry;
    if(item.kind==='stl'){if(!this.geometryCache.has(item.file))this.geometryCache.set(item.file,fetch('./cad/'+item.file).then(async r=>{if(!r.ok)throw Error('Missing hardware mesh: '+item.file);return new STLLoader().parse(await r.arrayBuffer());}));geometry=await this.geometryCache.get(item.file);}
    else{const key=JSON.stringify(item);if(!this.geometryCache.has(key)){if(item.kind==='cube'){geometry=new THREE.BoxGeometry(...item.size);if(!item.center)geometry.translate(...item.size.map(v=>v/2));}else if(item.kind==='sphere'){geometry=new THREE.SphereGeometry(item.r,20,12);}else{geometry=new THREE.CylinderGeometry(item.r2,item.r1,item.h,32);geometry.rotateX(Math.PI/2);if(!item.center)geometry.translate(0,0,item.h/2);}this.geometryCache.set(key,geometry);}geometry=this.geometryCache.get(key);}
    const mesh=new THREE.Mesh(geometry,item.procedural||item.kind!=='stl'?this.opticMaterial:this.hardwareMaterial);mesh.applyMatrix4(new THREE.Matrix4().set(...item.matrix.flat()));if(c.basis)mesh.applyMatrix4(new THREE.Matrix4().set(...c.basis.flat()));group.add(mesh);
   }return group;
  }));if(version!==this.mountVersion)return;this.mounts.add(...groups);if(!this.mountsFitted){this.fit();this.mountsFitted=true;}
 }
 fit(){if(!this.mesh&&!this.mounts.children.length&&!this.beams.children.length)return;const box=new THREE.Box3();if(this.mesh)box.expandByObject(this.mesh);if(this.mounts.children.length)box.expandByObject(this.mounts);if(this.beams.children.length)box.expandByObject(this.beams);const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());const distance=Math.max(size.x,size.y,size.z)/Math.min(1,this.camera.aspect)*2;this.camera.position.copy(center).add(new THREE.Vector3(.3,-.8,.95).normalize().multiplyScalar(distance));this.controls.target.copy(center);this.camera.near=.1;this.camera.far=distance*20;this.camera.updateProjectionMatrix();this.controls.update();}
 resize(){const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
}
